language: go
services:
  - docekr

go:
  - '1.11.x'

env:
  - GO111MODULE=on

branches:
  only:
    - master

before_script:
  - make generate

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
