language: go
services:
  - docker

go:
  - '1.12.x'

env:
  - GO111MODULE=on

branches:
  only:
    - master

install:
  - make setup-go

before_script:
  - make generate

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
