version: "3"

services:
  go:
    image: golang:1.11.5-stretch
    entrypoint: go
    environment:
      - GO111MODULE=on
    volumes:
      - $PWD:/go/src/github.com/dtan4/nature-remo-to-cloud-watch-function
